[package]
name = "thread_forever"
version = "0.1.0"
authors = ["king6cong <king6cong@gmail.com>"]

[dependencies]
log = "0.3"
error-chain = "0.11.0-rc.2"

[dev-dependencies]
lazy_static = "0.2"
env_logger = "0.3"
rand = "0.3"
